### ISSUE TITLE
Popups invisible in Chrome 90

### ISSUE THREAD

**Issue by darabos** [lynxkite/lynxkite#161]
The popups won't appear due to this change in `third_party/blink/renderer/core/html/resources/html.css`:
https://github.com/chromium/chromium/commit/2024c426de3346666cb45f9c65ad9dec2246be99

```css
popup:not(:-internal-popup-open) {
    display: none !important;
}
```

We have a `popup` element. It's unrelated to Chrome's popups, but it's still affected by this rule, and gets hidden.

That's an unexpected risk factor! I guess migrating off Angular.js would protect against this, but maybe there is something less invasive?

Anyway, we've got to make a quick fix for now.
